server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/face_detection?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: pwd@jicai123
    driver-class-name: com.mysql.jdbc.Driver


  #thymelea模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    enabled: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main
      exclude: WEB-INF/**
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: cn.edu.swpu.face_detection_register.model.bo

